### ISSUE TITLE
Test failure on Windows due to path separator

### ISSUE THREAD

**Issue by nanis** [garu/CPAN-Testers-Common-Client#9]
I am not sure where exactly things go wrong, but, FYI:
```perl
t\02-config.t ............... 1/?
#   Failed test 'transport_args content'
#   at t\02-config.t line 96.
#     Structures begin differing at:
#          $got->{id_file} = 'tcf _Oidmetabase_id.json'
#     $expected->{id_file} = 't\cf _Oid\metabase_id.json'
# Looks like you failed 1 test of 23.
```

This is with CPAN-Testers-Common-Client-0.11, and freshly built This is perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x64-multi-thread (RC2).

**Comment by nanis** [comment]
FYI: `git bisect` tells me:

```
ce1b3d1573b267c98c5b02814e4b5211bcc214b9 is the first bad commit
commit ce1b3d1573b267c98c5b02814e4b5211bcc214b9
Author: Breno G. de Oliveira <garu@cpan.org>
Date:   Thu Apr 21 17:57:13 2016 +0100

    improving transport argument parsing

:040000 040000 4b29b118d88f5ff7f9fddb0495bad3e4673270b4 348e89b07ba0cb10c686afa0ed7a58fbbd9f6837 M      lib
:040000 040000 fca2a666948a840cd444fe7193ae3976941935db 7fdfadf9c8cc8a24a09518f803da4ac29e8dcefd M  t
```

**Comment by nanis** [comment]
It looks like one or more replacements strings in regex substitutions end up interpolating a string containing `\` as directory separator.

**Comment by garu** [comment]
Hey @nanis, thanks for testing it on windows!

You're absolutely right! We remove "\\" from the path. Let me try and think of a solution real quick.

**Comment by nanis** [comment]
As a band aid, replacing:

```perl
$transport_args =~ s/(\bid_file\s+)(\S.+?)\s*$/$1"$id_file"/;
```

with

```perl
$transport_args =~ s/(\bid_file\s+)(\S.+?)\s*$/$1 . q{"} . quotemata($id_file) . q{"}/e;
```

worked for me ... which indicates the real source of the problem may be somewhere else.

**Comment by garu** [comment]
Interesting solution. I made a similar one but just placing the removed quotes back again. It's on master here and on CPAN as App::cpanminus::reporter 0.17.

Could you give it a go, please? And let me know if it works?

**Comment by garu** [comment]
To give you a bit more information, the patch was to allow paths with spaces in it. But the way it's implemented we need to have backslashes doubled if we're using them. So:

`"/some/path with spaces/to/my\"file.json"`

is converted to:

`/some/path with spaces/to/my"file.json`

but in windows, it means this path:

`"\some\path with spaces\to\myfile.json"`

will be (wrongly) converted to:

`somepath with spacestomyfile.json`

The solution is to always escape backslashes before calling the parser, so it instead requires you to double your backslashes in any paths that have spaces. This means that, if you have spaces but you're using windows, you should have paths like:

`"\\some\\path with spaces\\to\\myfile.json"`

which will become (correctly):

`"\some\path with spaces\to\myfile.json"`.

What your quotemeta (and my patch) is doing is fixing that for the parser so it DTRT.

**Comment by nanis** [comment]
As I said, mine was a band aid ;-) Thank you for addressing this issue.

```
C:\> cpanm App::cpanminus::reporter
--> Working on App::cpanminus::reporter
Fetching https://cpan.metacpan.org/authors/id/G/GA/GARU/App-cpanminus-reporter-0.17.tar.gz ... OK
Configuring App-cpanminus-reporter-0.17 ... OK
==> Found dependencies: CPAN::Testers::Common::Client
--> Working on CPAN::Testers::Common::Client
Fetching https://cpan.metacpan.org/authors/id/G/GA/GARU/CPAN-Testers-Common-Client-0.13.tar.gz ... OK
Configuring CPAN-Testers-Common-Client-0.13 ... OK
Building and testing CPAN-Testers-Common-Client-0.13 ... OK
Successfully installed CPAN-Testers-Common-Client-0.13 (upgraded from 0.12)
Building and testing App-cpanminus-reporter-0.17 ... OK
Successfully installed App-cpanminus-reporter-0.17 (upgraded from 0.15)
2 distributions installed

C:\> cpanm-reporter
sending: (https://cpan.metacpan.org/authors/id/G/GA/GARU/CPAN-Testers-Common-Client-0.13.tar.gz, GARU, CPAN-Testers-Common-Client-0.13, PASS)
sending: (https://cpan.metacpan.org/authors/id/G/GA/GARU/App-cpanminus-reporter-0.17.tar.gz, GARU, App-cpanminus-reporter-0.17, PASS)
```

**Comment by garu** [comment]
\o/
